Feature/extend policy
k-cloud-labs/pkg pull request #17
Opened 2022-11-04 07:01 UTC by yusank

2022-11-10 10:56 UTC, yusank commented
doc url: [https://k-cloud-labs.github.io/kinitiras-doc/](https://k-cloud-labs.github.io/kinitiras-doc)

2022-11-14 06:07 UTC, likakuli requested changes

2022-11-14 06:07 UTC, likakuli commented on Makefile
> +docs-generate: ## generate crd api docs
add dependency just as controller-gen

2022-11-14 06:07 UTC, likakuli commented on apis/policy/v1alpha1/clustervalidatepolicy_types.go
> +	//if there are any data added manually will be erased.
set first blank space

2022-11-14 06:07 UTC, likakuli commented on apis/policy/v1alpha1/overridepolicy_types.go
> +type HttpDataRef struct {
not support https for now?

2022-11-14 06:07 UTC, likakuli commented on go.mod
> +	k8s.io/code-generator v0.23.0
why fallback to v0.23.0?

2022-11-14 07:28 UTC, yusank commented on apis/policy/v1alpha1/overridepolicy_types.go
> +type HttpDataRef struct {
There is no enough time to support `https` and `http auth`

2022-11-14 10:32 UTC, likakuli requested changes

2022-11-14 10:32 UTC, likakuli commented on utils/cue/params.go
> +		obj, err := rc.Namespace(refNs).Get(ctx, refName, metav1.GetOptions{})
There are performance problem when too many policy using remote resource. Can keep like this this time but need to do this next time.

2022-11-14 10:32 UTC, likakuli commented on utils/cue/params.go
> +		list, err := rc.Namespace(rs.Namespace).List(ctx, metav1.ListOptions{
same as above

2022-11-14 10:32 UTC, likakuli commented on utils/cue/params.go
> +	return rc.Namespace(obj.GetNamespace()).Get(ctx, or.Name, metav1.GetOptions{})
same as above

2022-11-14 10:32 UTC, likakuli commented on apis/policy/v1alpha1/overridepolicy_types.go
> +	// If current type is annotations of labels, then only need to provide the key, no need whole path.
annotations of labels, of to or

2022-11-16 02:29 UTC, yusank commented on utils/cue/params.go
> +		obj, err := rc.Namespace(refNs).Get(ctx, refName, metav1.GetOptions{})
working on it.

2022-11-22 08:32 UTC, merged